version: '3'


services:
  db:
    image: postgres:latest
    container_name: restaurant-postgres
    environment:
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_USER: 'root'
      POSTGRES_DB: 'postgres' # create a db by default
    ports:
      - "5455:5432"
    restart: unless-stopped

# force containers to join mynetwork
networks:
  mynetwork:
    external: true
volumes:
  postgres_data: